### PR TITLE
Nil Error

### LINKED ISSUE #423: PlugConnWrapperError happened in Healthlocker.SleepTrackerController#create
**Message**

```
  HTTP request error: ** (FunctionClauseError) no function clause matching in String.Unicode.next_grapheme_size/1
```

**Backtrace (last 10 lines)**

```
(elixir) unicode/unicode.ex:190: String.Unicode.length/1
(healthlocker) lib/healthlocker/analytics/properties_builder.ex:17: Healthlocker.Analytics.PropertiesBuilder.properties/1
(healthlocker) lib/healthlocker/analytics.ex:34: Healthlocker.Analytics.track/3
(healthlocker) web/controllers/sleep_tracker_controller.ex:72: Healthlocker.SleepTrackerController.create/2
(healthlocker) web/controllers/sleep_tracker_controller.ex:1: Healthlocker.SleepTrackerController.action/2
(healthlocker) web/controllers/sleep_tracker_controller.ex:1: Healthlocker.SleepTrackerController.phoenix_controller_pipeline/2
(healthlocker) lib/healthlocker/endpoint.ex:1: Healthlocker.Endpoint.instrument/4
```

View on AppSignal: https://appsignal.com/healthlocker/sites/58ee002122139305bcd5267a/incidents/45

### PR DESCRIPTION
**Pull request by tonydaly**
If `sleep_data.notes` is left blank it'll be set to `nil`, we can't check the length of nil, so instead coerce it to a bool and use that for the property. Fixes #423.

### CODE REVIEW

File: lib/healthlocker/analytics/properties_builder.ex [hunk 1]
```diff
@@ -10,11 +11,10 @@ defmodule Healthlocker.Analytics.PropertiesBuilder do
     }
   end
 
-  defp properties(%Healthlocker.Post{} = coping_strategy), do: %{}
-
+  defp properties(%Healthlocker.Post{}), do: %{}
   defp properties(%Healthlocker.SleepTracker{} = sleep_data) do
     %{
-      notes: String.length(sleep_data.notes) > 0
+      notes: !!sleep_data.notes
```
Comment (nelsonic) [inline lib/healthlocker/analytics/properties_builder.ex]: might be worth having a comment to explain what the `!!` does ... ?
